{% set name = "fps-auth-jupyterhub" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_auth_jupyterhub-{{ version }}.tar.gz
  sha256: 02882a7a2da5ab15ba2044c4b6a13b0ae17da5a33f91237ad848ea5523e96ed3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - jupyverse-api >=0.1.4,<1
    - asphalt-sqlalchemy >=5.0.1,<6
    - httpx >=0.24.1,<1
    - jupyterhub >=4.0.1,<5

test:
  imports:
    - fps_auth_jupyterhub

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth_jupyterhub
  summary: An FPS plugin for the authentication API, using JupyterHub
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth_jupyterhub
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
