{% set name = "fps-auth-jupyterhub" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_auth_jupyterhub-{{ version }}.tar.gz
  sha256: 15048ad31d3535fb98062aa5baaadea7ca64c4d3b1ef6ea37756c6abefc6c40d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.7.0,<1
    - anyio
    - aiosqlite
    - httpx >=0.24.1,<1
    - jupyterhub >=4.0.1,<5

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_auth_jupyterhub

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth_jupyterhub
  summary: An FPS plugin for the authentication API, using JupyterHub
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth_jupyterhub
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
